"""
Project: CsvToDBF
Author: Sabariram
Date: 15-Jun-2023
"""

KARVY_DBF_COLUMN_LIST = [
    "FMCODE C(10)",
    "TD_FUND C(4)",
    "TD_ACNO N(18,0)",
    "SCHPLN C(4)",
    "FUNDDESC C(200)",
    "TD_PURRED C(1)",
    "TD_TRNO N(10,0)",
    "SMCODE N(10,0)",
    "CHQNO C(20)",
    "INVNAME C(80)",
    "TRNMODE C(1)",
    "TRNSTAT C(1)",
    "TD_BRANCH C(50)",
    "ISCTRNO N(10,0)",
    "TD_TRDT D",
    "TD_PRDT D",
    "TD_POP C(30)",
    "TD_UNITS N(20,3)",
    "TD_AMT N(20,2)",
    "TD_AGENT C(20)",
    "TD_BROKER C(20)",
    "BROKPER N(18,0)",
    "BROKCOMM N(18,0)",
    "INVID C(1)",
    "CRDATE D",
    "CRTIME C(6)",
    "TRNSUB C(1)",
    "TD_APPNO C(20)",
    "UNQNO C(50)",
    "TRDESC C(40)",
    "TD_TRTYPE C(10)",
    "CHQDATE D",
    "CHQBANK C(40)",
    "DIVOPT C(1)",
    "PURAMT N(20,2)",
    "PURDATE D",
    "SFUNDDT D",
    "TRFLAG C(5)",
    "TD_NAV C(30)",
    "TD_PTRNO N(10,0)",
    "STT N(20,2)",
    "LOADPER N(18,4)",
    "LOAD1 N(20,2)",
    "PURUNITS N(20,3)",
    "IHNO N(15,0)",
    "BRANCHCODE C(10)",
    "INWARDNUM0 C(25)",
    "PAN1 C(20)",
    "NCTREMARKS C(200)",
    "NAVDATE D",
    "PAN2 C(20)",
    "PAN3 C(20)",
    "TDSAMOUNT N(20,2)",
    "SCH1 C(4)",
    "PLN1 C(4)",
    "PRCODE1 C(10)",
    "TD_TRXNMO1 C(20)",
    "CLIENTID C(20)",
    "DPID C(20)",
    "STATUS C(20)",
    "REJTRNOOR2 C(20)",
    "SUBTRTYPE C(30)",
    "TRCHARGES N(20,2)",
    "ATMCARDST3 C(30)",
    "ATMCARDRE4 C(250)",
    "BROK_ENTDT D",
    "SCHEMEISIN C(30)",
    "CITYCATEG5 C(50)",
    "PORTDT D",
    "NEWUNQNO C(200)",
    "EUIN C(20)",
    "SUBARNCODE C(40)",
    "EVALID C(40)",
    "EDECLFLAG C(40)",
    "ASSETTYPE C(30)",
    "SIPREGDT D",
    "DIVPER N(20,10)",
    "GUARDPANNO C(20)",
    "CAN C(30)",
    "EXCHORGTR6 C(20)",
    "ELECTRXNF7 C(1)",
    "STAMPDUTY N(13,2)"
]

KAFVY_CSV_TO_DBF_MAP = {
    "Product Code": "FMCODE",
    "Fund": "TD_FUND",
    "Folio Number": "TD_ACNO",
    "Scheme Code": "SCHPLN",
    "Fund Description": "FUNDDESC",
    "Transaction Head": "TD_PURRED",
    "Transaction Number": "TD_TRNO",
    "Switch_Ref. No.": "SMCODE",
    "Instrument Number": "CHQNO",
    "Investor Name": "INVNAME",
    "Transaction Mode": "TRNMODE",
    "Transaction Status": "TRNSTAT",
    "Branch Name": "TD_BRANCH",
    "Branch Transaction No": "ISCTRNO",
    "Transaction Date": "TD_TRDT",
    "Process Date": "TD_PRDT",
    "Price": "TD_POP",
    "Units": "TD_UNITS",
    "Amount": "TD_AMT",
    "Agent Code": "TD_AGENT",
    "Sub-Broker Code": "TD_BROKER",
    "Brokerage Percentage": "BROKPER",
    "Commission": "BROKCOMM",
    "Investor ID": "INVID",
    "Report Date": "CRDATE",
    "Report Time": "CRTIME",
    "Transaction Sub": "TRNSUB",
    "Application Number": "TD_APPNO",
    "Transaction ID": "UNQNO",
    "Transaction Description": "TRDESC",
    "Transaction Type": "TD_TRTYPE",
    "Instrument Date": "CHQDATE",
    "Instrument Bank": "CHQBANK",
    "Dividend Option": "DIVOPT",
    "Purchase Amount": "PURAMT",
    "Purchase Date": "PURDATE",
    "Switch Fund Date": "SFUNDDT",
    "Transaction Flag": "TRFLAG",
    "Nav": "TD_NAV",
    "Purchase Transaction No": "TD_PTRNO",
    "STT": "STT",
    "Load Percentage": "LOADPER",
    "Load Amount": "LOAD1",
    "Purchase Units": "PURUNITS",
    "Ihno": "IHNO",
    "Branch Code": "BRANCHCODE",
    "Inward Number": "INWARDNUM0",
    "PAN1": "PAN1",
    "Remarks": "NCTREMARKS",
    "Nav Date": "NAVDATE",
    "PAN2": "PAN2",
    "PAN3": "PAN3",
    "TDSAmount": "TDSAMOUNT",
    "Scheme": "SCH1",
    "Plan": "PLN1",
    "ToProductCode": "PRCODE1",
    "td_trxnmode": "TD_TRXNMO1",
    "ClientId": "CLIENTID",
    "DpId": "DPID",
    "Status": "STATUS",
    "RejTrnoOrgNo": "REJTRNOOR2",
    "SubTranType": "SUBTRTYPE",
    "TrCharges": "TRCHARGES",
    "ATMCardStatus": "ATMCARDST3",
    "ATMCardRemarks": "ATMCARDRE4",
    "NCT Change Date": "BROK_ENTDT",
    "ISIN": "SCHEMEISIN",
    "CityCategory": "CITYCATEG5",
    "PortDate": "PORTDT",
    "NewUnqno": "NEWUNQNO",
    "EUIN": "EUIN",
    "Sub Broker RIA Code": "SUBARNCODE",
    "EUIN Valid Indicator": "EVALID",
    "EUIN Declaration Indicator": "EDECLFLAG",
    "AssetType": "ASSETTYPE",
    "SIP Regn Date": "SIPREGDT",
    "DivPer": "DIVPER",
    "GuardPanNo": "GUARDPANNO",
    "Common Account Number": "CAN",
    "Exchange OrgTrType": "EXCHORGTR6",
    "Electronic transaction Flag": "ELECTRXNF7",
    "Stamp Duty Charges": "STAMPDUTY"
}


def get_column_map():
    return KAFVY_CSV_TO_DBF_MAP, KARVY_DBF_COLUMN_LIST
